language: php

php:
  - 5.3
  - 5.4

before_script: composer install --dev --prefer-dist

script: php bin/phpspec run -f pretty

notifications:
  email: travis-ci@sylius.org
  irc: "irc.freenode.org#sylius-dev"
