# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_backend_option_list:
    pattern: /list
    defaults: { _controller: sylius_assortment.controller.backend.option:listAction }

sylius_assortment_backend_option_create:
    pattern: /create
    defaults: { _controller: sylius_assortment.controller.backend.option:createAction }

sylius_assortment_backend_option_update:
    pattern: /{id}/update
    defaults: { _controller: sylius_assortment.controller.backend.option:updateAction }

sylius_assortment_backend_option_delete:
    pattern: /{id}/delete
    defaults: { _controller: sylius_assortment.controller.backend.option:deleteAction }
