sylius_assortment_backend_product_list:
    pattern: /products
    defaults: { _controller: sylius_assortment.controller.backend.product:listAction }

sylius_assortment_backend_product_create:
    pattern: /product/create
    defaults: { _controller: sylius_assortment.controller.backend.product:createAction }
    
sylius_assortment_backend_product_update:
    pattern: /product/{id}/update
    defaults: { _controller: sylius_assortment.controller.backend.product:updateAction }
        
sylius_assortment_backend_product_delete:
    pattern: /product/{id}/delete
    defaults: { _controller: sylius_assortment.controller.backend.product:deleteAction }
    
sylius_assortment_backend_product_show:
    pattern: /product/{id}
    defaults: { _controller: sylius_assortment.controller.backend.product:showAction }
