# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_backend_prototype_list:
    pattern: /list
    defaults: { _controller: sylius_assortment.controller.backend.prototype:listAction }

sylius_assortment_backend_prototype_create:
    pattern: /create
    defaults: { _controller: sylius_assortment.controller.backend.prototype:createAction }

sylius_assortment_backend_prototype_update:
    pattern: /{id}/update
    defaults: { _controller: sylius_assortment.controller.backend.prototype:updateAction }

sylius_assortment_backend_prototype_delete:
    pattern: /{id}/delete
    defaults: { _controller: sylius_assortment.controller.backend.prototype:deleteAction }
