# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_backend_property_list:
    pattern: /list
    defaults: { _controller: sylius_assortment.controller.backend.property:listAction }

sylius_assortment_backend_property_create:
    pattern: /create
    defaults: { _controller: sylius_assortment.controller.backend.property:createAction }

sylius_assortment_backend_property_update:
    pattern: /{id}/update
    defaults: { _controller: sylius_assortment.controller.backend.property:updateAction }

sylius_assortment_backend_property_delete:
    pattern: /{id}/delete
    defaults: { _controller: sylius_assortment.controller.backend.property:deleteAction }
