# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_option_new:
    pattern: /new
    defaults:
        _controller: sylius_assortment.controller.option:newAction
    requirements:

sylius_assortment_option_post:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.option:postAction
        _sylius.redirect: sylius_assortment_option
    requirements:
        _method: POST

sylius_assortment_option_edit:
    pattern: /{id}/edit
    defaults:
        _controller: sylius_assortment.controller.option:editAction
    requirements:
        _method: GET

sylius_assortment_option_put:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.option:putAction
        _sylius.redirect: sylius_assortment_option
    requirements:
        _method: PUT|POST

sylius_assortment_option_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_assortment.controller.option:deleteAction
        _sylius.redirect: sylius_assortment_options
    requirements:
        _method: GET

sylius_assortment_options:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.option:getCollectionAction
    requirements:
        _method: GET

sylius_assortment_option:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.option:getAction
    requirements:
        _method: GET
