# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_property_new:
    pattern: /new
    defaults:
        _controller: sylius_assortment.controller.property:newAction
    requirements:

sylius_assortment_property_post:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.property:postAction
        _sylius.redirect: sylius_assortment_property
    requirements:
        _method: POST

sylius_assortment_property_edit:
    pattern: /{id}/edit
    defaults:
        _controller: sylius_assortment.controller.property:editAction
    requirements:
        _method: GET

sylius_assortment_property_put:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.property:putAction
        _sylius.redirect: sylius_assortment_property
    requirements:
        _method: PUT|POST

sylius_assortment_property_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_assortment.controller.property:deleteAction
        _sylius.redirect: sylius_assortment_properties
    requirements:
        _method: GET

sylius_assortment_properties:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.property:getCollectionAction
    requirements:
        _method: GET

sylius_assortment_property:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.property:getAction
    requirements:
        _method: GET
