# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_prototype_new:
    pattern: /new
    defaults:
        _controller: sylius_assortment.controller.prototype:newAction
    requirements:

sylius_assortment_prototype_post:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.prototype:postAction
        _sylius.redirect: sylius_assortment_prototype
    requirements:
        _method: POST

sylius_assortment_prototype_edit:
    pattern: /{id}/edit
    defaults:
        _controller: sylius_assortment.controller.prototype:editAction
    requirements:
        _method: GET

sylius_assortment_prototype_put:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.prototype:putAction
        _sylius.redirect: sylius_assortment_prototype
    requirements:
        _method: PUT|POST

sylius_assortment_prototype_delete:
    pattern: /{id}/delete
    defaults:
        _controller: sylius_assortment.controller.prototype:deleteAction
        _sylius.redirect: sylius_assortment_prototypes
    requirements:
        _method: GET

sylius_assortment_prototypes:
    pattern: /
    defaults:
        _controller: sylius_assortment.controller.prototype:getCollectionAction
    requirements:
        _method: GET

sylius_assortment_prototype_build:
    pattern: /{id}/build
    defaults:
        _controller: sylius_assortment.controller.prototype:getAction
    requirements:
        _method: GET

sylius_assortment_prototype:
    pattern: /{id}
    defaults:
        _controller: sylius_assortment.controller.prototype:getAction
    requirements:
        _method: GET
