# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_assortment_product_list:
    pattern: /
    defaults: { _controller: sylius_assortment.controller.frontend.product:listAction }

sylius_assortment_product_show:
    pattern: /{slug}
    defaults: { _controller: sylius_assortment.controller.frontend.product:showAction }
