sylius_assortment_product_show:
    pattern: /{id}/{slug}
    defaults: { _controller: sylius_assortment.controller.frontend.product:showAction }
    
sylius_assortment_product_list:
    pattern: /list
    defaults: { _controller: sylius_assortment.controller.frontend.product:listAction }
